app_name: "FaloppiaWarn"

# PLIVO SMS Framework
plivo_auth_id: "SANME2YTDKYZHJYZEWZG"
plivo_auth_token: "OWMxNDM4OGY4NTEzYWU2NGZkNjMyYzY2NTA0ZDQ5"


#Authentication
username: 'faloppia'
password: 'alveo666'

# SMS numbers
sender_number: "+41792158388"
alert_numbers:
  level_0:
    # this numbers receive an sms each time a calculation is run even if the
    # result of the analysis is StandardAlertLevels.no_alert
    # it is used for debugging
    - "+41794672470"
  level_1:
    - "+41794672470"
    # - "+41791960173"
  level_2:
    - "+41794672470"
    # - "+41791960173"

it_alert_numbers:
  # this is for technical issues on the software side
  - "+41794672470"
  #- "+41791960173"


# {} is replaced with the details of the alert
alert_text:
  level_-1: "IT Problem, {}"
  level_0: "Notifica, {}"
  level_1: "Allerta, {}"
  level_2: "ALLARME, {}"


# can be FATAL, ERROR, WARNING, INFO, DEBUG, NOTSET
log_level: 'DEBUG'

timezone: 'Europe/Zurich'

parsers:
  cpc:
    active: false
    update: 5
    data_path: "data/cpc"
    tresholds:
      level_1:
        - ["allerta precipitazione: 5 mm su 12 h (6h misurate e 6h previste)"]
        - ["allerta precipitazione: 30 mm su 12 h (6h misurate e 6h previste)"]
      level_2:
        - ["allarme precipitazione: 5 mm su 60 minuti (30 minuti misurati e 30 minuti previsti)"]

  oasi:
    active: true
    update: 5
    data_path: "data/oasi"
    timespan: 1
    thresholds:
      level_1:
        - ["{0} > 2.0 and {0} <= 5.0", "deflusso superiore ai 2.0 m3/s ({}) raggiunto alle {} -> L'impresa si prepara ad un'eventuale evacuazione e controlla l'evoluzione delle precipitazioni e del deflusso."]
      level_2:
        - ["{0} > 5.0", "deflusso superiore ai 5.0 m3/s ({}) raggiunto alle {} -> L'impresa evacua il cantiere entro 15 minuti."]
        - ["{0} < 0.1", "deflusso inferiore ai 0.1 m3/s ({}) raggiunto alle {} -> L‘impresa evacua il cantiere entro 15 minuti e smantella la rampa d'accesso entro 2 ore."]

  meteogram:
    active: false
    update: 5
    data_path: "data/meteogram"
