app_name: "FaloppiaWarn"

# PLIVO SMS Framework
plivo_auth_id: "SANME2YTDKYZHJYZEWZG"
plivo_auth_token: "OWMxNDM4OGY4NTEzYWU2NGZkNjMyYzY2NTA0ZDQ5"


#Authentication
username: faloppia
password: alveo666

# SMS numbers
sender_number: "+41792158388"
alert_numbers:
  level_0:
    # this numbers receive an sms each time a calculation is run even if the
    # result of the analysis is StandardAlertLevels.no_alert
    # it is used for debugging
    - "+41794672470"
  level_1:
    - "+41794672470"
    - "+41791960173"
  level_2:
    - "+41794672470"
    # - "+41791960173"

it_alert_numbers:
  # this is for technical issues on the software side
  - "+41794672470"
  #- "+41791960173"


# {} is replaced with the details of the alert
alert_text:
  level_-1: "IT Problem, {}"
  level_0: "Notifica, {}"
  level_1: "Allerta, {}"
  level_2: "ALLARME, {}"


# can be FATAL, ERROR, WARNING, INFO, DEBUG, NOTSET
log_level: 'DEBUG'


parsers:
  CombiPrecip:
    update: 5
    data_path: "data/cpc"
  OASI:
    update: 5
    data_path: "data/oasi"
